version: '3.8'

services:
  snakey:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'snakepy'

  snake_test:
    build:
      context: ./docker_
      dockerfile: Dockerfile
    image: 'snakepy2'
    depends_on:
      - snakey
    command: pytest -s -v

